Адаптивная сетка
htmlacademy-adaptive/2073605-sedona-26 pull request #4
Opened 2022-08-25 06:52 UTC by Yurii1980

2022-08-26 17:52 UTC, andreysgra requested changes

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/page-wrapper.scss
> +    width: 1280px;
1. Неверно определён переход на десктопную версию (это касается всего проекта в целом, а не только блока `page-wrapper`). В [Б11](https://up.htmlacademy.ru/adaptive/26/criteries#b11) указаны вьюпоты для всех проектов. Для седоны это 1200px.
2. Почему `width: 1280px`? Ширина контентной области в макете десктопной версии определяется расстоянием между направляющими:
![image](https://user-images.githubusercontent.com/17790771/186958087-cf2d31ff-ccd4-45e1-a682-4ca78f87b611.png)

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/main-header.scss
>    margin: 0 auto;
Какой смысл в этом свойстве, если центрирование контента производится общим блоком `page-wrapper`?

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/reality.scss
>  }
У списка `reality` не помешало бы обнулить дефолтный паддинг слева:
![image](https://user-images.githubusercontent.com/17790771/186958969-e56aef79-0b48-428e-b2b1-5a96d5a7cc9b.png)

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/reality.scss
> +  }
Паддинги у элемента списка это хорошо, но не мешает элементу явно задать ширину согласно макета, иначе это приводит к тому, что ширина зависит от контента.
Планшетная версия:
![image](https://user-images.githubusercontent.com/17790771/186959428-8767b785-9876-445f-8571-4e702d5d2882.png)
![image](https://user-images.githubusercontent.com/17790771/186959476-89808ded-39ec-4d15-8df8-ba3400a9bd01.png)

Десктопная версия:
![image](https://user-images.githubusercontent.com/17790771/186959667-920299e3-9eb9-4916-b57e-5235e1723a63.png)
![image](https://user-images.githubusercontent.com/17790771/186959858-c1edb382-0b37-495a-bcfd-9ff60b19c5fd.png)

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/media.scss
> +@media (min-width: 768px) {
Начиная с планшетной версии блоку `media` стоит определить горизонтальные паддинги, чтобы контент галереи выровнять согласно макета.

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/photo.scss
> +  .photo:nth-child(1) {
Первому элементу галереи можно задать ширину просто 100%, чтобы он занял всё свободное пространство.

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/modal-container.scss
> +}
В этом блоке нет никакой необходимости использовать `flex`. Элементы блока идут друг под другом, значит здесь лучше всего подходит блочная модель. Но вы зачем-то используете флекс, в котором элементы по умолчанию расположены горизонтально, а затем поворачиваете главную ось (`flex-direction: column`) эмулируя этим блочное поведение.

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/form.scss
> +@media (min-width: 768px) {
Начиная с планшетной версии форма не занимает всё доступное пространство и чтобы расположить её элементы по макету секции `form` логичнее задать горизонтальные паддинги.

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/form.scss
> +    flex-direction: column;
Нужен ли здесь `flex`? О ненужной эмуляции блочного поведения через `flex` написал выше.

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/main-footer.scss
> +  }
Эти свойства вы задали в `@media (min-width: 768px)`, но здесь ничего не меняется, так что смысла в дублировании тех же свойств нет.

2022-08-26 17:52 UTC, andreysgra commented on source/sass/blocks/main-header.scss
> +}
Точно также и здесь.

2022-08-27 11:50 UTC, Yurii1980 commented
Андрей, добрый день.
Подскажите, пожалуйста, в чем может быть проблема.
В браузере инспектор показывает margin 8 px для body, хотя задал класс для него и margin 0. Проверил style.css сборка файла page-site.scss не произошла.

2022-08-27 12:44 UTC, Yurii1980 commented
Андрей, все в порядке. Разобрался. Все работает.

2022-08-28 12:50 UTC, merged