Автоматизация сборки личного проекта
htmlacademy-adaptive/2073605-sedona-26 pull request #8
Opened 2022-09-15 19:31 UTC by Yurii1980

---
:mortar_board: [Автоматизация сборки личного проекта](https://up.htmlacademy.ru/adaptive/26/user/2073605/tasks/12)

:boom: https://htmlacademy-adaptive.github.io/2073605-sedona-26/8/

2022-09-16 07:11 UTC, andreysgra requested changes
Нужно внести корректировки в задание `styles`. После автоматизации проекта сборка идёт в папке `build`, а задание `styles` собирает файл стилей в папке `source`.
1. Изменить путь к конечной папке.
2. Добавить минификацию готового CSS.
3. Изменить в HTML название файла CSS на css/style.min.css, так как сжатый файл теперь будет называться style.min.css.

Первые два пункта выполняются в рамках задания `styles`.

2022-09-16 19:56 UTC, Yurii1980 commented
Андрей, добрый день.
Все вроде сделал, но сборка не работает, стили не подключаются, выводится только один HTML и никакого CSS.

2022-09-17 07:02 UTC, andreysgra requested changes
> стили не подключаются, выводится только один HTML и никакого CSS

Потому что вы не выполнили пункт 3 из моего комментария к первой проверке. Файл стилей теперь называется **style.min.css**, а  в html подключен по-прежнему **style.css**. 

---

Эти файлы из проекта нужно удалить:
![image](https://user-images.githubusercontent.com/17790771/190844661-488039ee-566f-481c-9318-1c84fdc1a9c6.png)
Что это за папка `sourse`?
![image](https://user-images.githubusercontent.com/17790771/190844693-07568fdb-a7b7-4c49-8cc1-797d7238b38f.png)

2022-09-17 07:02 UTC, andreysgra commented on gulpfile.js
> +}
В этих двух заданиях Gulp производится простое копирование файлов: `gulp.src -> gulp.dest`. По-хорошему здесь должно производиться сжатие файлов html и js. Если это не собираетесь делать, то копирование html и js стоит описать в задании `copy`, там где вы копируете шрифты и иконки.

2022-09-17 08:32 UTC, Yurii1980 commented
Почти все заработало. Кроме фавиконки (ее нет) и размер на главном изображении не меняется на планшетной и десктопной версиях.

2022-09-18 06:51 UTC, merged